{% set name = "diffpy.fourigui" %}
{% set version = "0.2.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/d/diffpy_fourigui/diffpy_fourigui-{{ version }}.tar.gz
  sha256: 20e2d7965f5ba6c6ce8f367c54ab396cf8e2732a5ecde56afc33add9af3cad8e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .

requirements:
  build:

  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - h5py
    - tk
    - matplotlib-base
    - numpy

test:
  requires:
    - python {{ python_min }}
    - pytest-mock
    - pytest

  source_files:
    - tests

  commands:
    - pip check

about:
  home: https://github.com/diffpy/diffpy.fourigui/
  summary: A Python package for for visualizing 3D diffraction and PDF Images.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    Diffpy.fourigui is a tool to visualize and process 3D data sets written with the Python programming language. Diffpy.fourigui always displays one slice perpendicular to one axis and allows scrolling through the 3D data set along the given axis with a slider. It shows feedback values such as global and local maxima, minima or NAN ratios. The matplotlib panel e.g. for zooming and saving figures is featured. Diffpy.fourigui is designed for the processing of 3D atomic pair distribution functions (PDFs). One can load a 3D reciprocal space scattering volume which can be Fourier transformed to the 3D PDF. Thereby, one can apply cut off frequencies beyond and below given Q values, compare the results and switch between the scattering volume in reciprocal space and 3D PDF in real space.
  doc_url: http://diffpy.github.io/diffpy.fourigui/
  dev_url: https://github.com/diffpy/diffpy.fourigui/

extra:
  recipe-maintainers:
    - sbillinge
    - bobleesj
