{% set name = "diffpy.fourigui" %}
{% set version = "0.1.0rc2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://test.pypi.io/packages/source/d/diffpy_fourigui/diffpy_fourigui-{{ version }}.tar.gz
  sha256: 7f5f7b3941f070766f698e183849ff3c027f289a47e3aff18b48074646767532
build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python >=3.11,<3.14
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >=3.11,<3.14
    - h5py
    - tk
    - matplotlib-base
    - numpy

test: 
  requires:
    - pip
    - pytest
    - flake8
    - pytest
    - codecov
    - coverage
    - pytest-cov
    - pytest-env
    - pytest-mock

  source_files:
    - tests

about:
  home: https://github.com/diffpy/diffpy.fourigui/
  summary: A Pyhton package for for visualizing 3D diffraction and PDF Images.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    A Pyhton package for for visualizing 3D diffraction and PDF Images.
  doc_url: https://diffpy.github.io/diffpy.fourigui/
  dev_url: https://github.com/diffpy/diffpy.fourigui/

extra:
  recipe-maintainers:
    - sbillinge
    - bobleesj
