{% set name = "diffpy.fourigui" %}
{% set version = "0.2.0" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/diffpy_fourigui/diffpy_fourigui-{{ version }}.tar.gz
  sha256: 20e2d7965f5ba6c6ce8f367c54ab396cf8e2732a5ecde56afc33add9af3cad8e
build:
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - setuptools-git-versioning >=2.0
    - pip

  run:
    - python >={{ python_min }}
    - h5py
    - tk
    - matplotlib-base
    - numpy

test: 
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - pytest-mock

  source_files:
    - tests

about:
  home: https://github.com/diffpy/diffpy.fourigui/
  summary: A Python package for for visualizing 3D diffraction and PDF Images.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  description: |
    A Python package for for visualizing 3D diffraction and PDF Images.
  doc_url: https://diffpy.github.io/diffpy.fourigui/
  dev_url: https://github.com/diffpy/diffpy.fourigui/

extra:
  recipe-maintainers:
    - sbillinge
    - bobleesj
